### ISSUE TITLE
Action fails: references to workflows must be rooted in '.github/workflows'

### ISSUE THREAD

**Issue by Syzygianinfern0** [JamieMagee/wayback#118]
I'm not sure what I'm doing wrong. Please help me out. The log is [here](https://github.com/Syzygianinfern0/Syzygianinfern0.github.io/actions/workflows/archive.yaml).

**Comment by JamieMagee** [comment]
You're missing the `steps` property. Currently you have

```yml
jobs:
  archive:
    name: Wayback Machine
    uses: JamieMagee/wayback@v1.3.19
    with:
      url: spsharan.com
```

but you should have

```yml
jobs:
  archive:
    steps:
      - name: Wayback Machine
    	uses: JamieMagee/wayback@v1.3.19
        with:
          url: spsharan.com
```

Check out the GitHub Actions workflow syntax documentation[^1] for a complete reference

[^1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
